backend/.gitignore, backend/dist/controllers/UserController.js, backend/dist/models/userModal.js, backend/dist/routes/userRoute.js, backend/dist/server.js, backend/src/controllers/UserController.ts, backend/src/models/userModal.ts, backend/src/routes/userRoute.ts, backend/src/server.ts
Created endpoint for creating users on cloud DB
=> added create user

backend/dist/controllers/UserController.js, backend/dist/routes/userRoute.js, backend/src/controllers/UserController.ts, backend/src/routes/userRoute.ts
- added GetUserByID and DeleteUserByID
=> 14 delete user endpoints

backend/dist/controllers/UserController.js, backend/dist/routes/userRoute.js, backend/src/controllers/UserController.ts, backend/src/routes/userRoute.ts
-Added patch users based of field
=> 13 patch user endpoints

backend/dist/controllers/UserController.js, backend/dist/models/userModal.js, backend/dist/routes/userRoute.js, backend/src/controllers/UserController.ts, backend/src/models/userModal.ts, backend/src/routes/userRoute.ts
Added two new fields to users collections
=> 17 add image and age in user documentscollections

backend/dist/controllers/AuthController.js, backend/dist/models/userModal.js, backend/dist/routes/authRoute.js, backend/dist/server.js, backend/package-lock.json, backend/package.json, backend/src/controllers/AuthController.ts, backend/src/models/userModal.ts, backend/src/routes/authRoute.ts, backend/src/routes/userRoute.ts, backend/src/server.ts
=> 7 authenticate and authorize users

backend/dist/models/scheduleModel.js, backend/src/models/scheduleModel.ts
=> added schedule Schema

backend/dist/controllers/ScheduleController.js, backend/dist/routes/scheduleRoute.js, backend/src/controllers/ScheduleController.ts, backend/src/routes/authRoute.ts, backend/src/routes/scheduleRoute.ts
- PATCH on basic fields `updateSchedule`
- PATCH on timeSlot object array `updateTimeSlot`
- DELETE on timeSlot items `deleteTimeSlot`
- error checking
=> 37 patch schedule endpoints

backend/dist/controllers/ScheduleController.js, client/package-lock.json, client/package.json
=> 53 install redux in cli

client/src/App.tsx, client/src/components/Account/AccountBox.tsx, client/src/components/Account/ProfilePic.tsx, client/src/components/Account/Tab.tsx, client/src/components/Logos/Edit.tsx, client/src/pages/Account.tsx
_**NOTES:**_ We need to configure Tab Component to render multiple pages.
=> 64 create tsx + styling account page

backend/dist/controllers/ScheduleController.js, backend/dist/controllers/UserController.js, backend/src/controllers/ScheduleController.ts, backend/src/controllers/UserController.ts
Refactoring CRUD endpoints to return the data that has been changed.
=> 57 refactor server controllers

client/src/components/Account/AccountBox.tsx, client/src/components/Account/Personal/PersonalTab.tsx, client/src/components/Account/Profile/ProfileTab.tsx, client/src/components/Account/Tab.tsx, client/src/index.css, client/src/pages/Account.tsx
- Fixing tabs onActive styling.
- Fixing positioning of the dropdown menu.
- Adding responsive styles.
=> Fixing account styling

client/package-lock.json, client/package.json, client/src/App.tsx, client/src/pages/Schedule.tsx
1) Changed the DB to be a string with a space in AM/PM. 
2) Created basic logic like, checking if StartTime or endTime are the same, 
3) Gives total time between start and end times.
=> 75 create proper timeslot

client/package-lock.json, client/package.json, client/src/App.tsx, client/src/components/Account/AccountBox.tsx, client/src/components/Account/Personal/PersonalTab.tsx, client/src/components/Account/Tab.tsx, client/src/components/Navbar.tsx, client/src/pages/Account.tsx
- Added the navbar to be used across the whole app. 
- Logic for the logged in user conditional rendering is still missing. 
- Some links to some pages are missing. 
- Added the Tailwindcss Prettier Plugin to order tailwind's classes correctly.
=> Adding basic navbar layout. Some links are still missing.

client/src/components/Login/LoginBox.tsx, client/src/components/Login/LoginForm.tsx, client/src/components/Signup/SignUpBox.tsx, client/src/pages/Login.tsx, client/src/pages/Signup.tsx
**_NOTES_**: Images will render only after medium/large breakpoints
=> 80 fix responsiveness on pages

backend/dist/controllers/UserController.js, backend/dist/models/userModel.js, backend/src/controllers/UserController.ts, backend/src/models/userModel.ts
- added Major field in all documents in User's collection
- Can perform CRUD operations as normal
=> added major field

client/src/components/findUsers/User.tsx, client/src/components/findUsers/UserContainer.tsx, client/src/pages/FindUser.tsx
This PR adds the filters for school and major in the find users page. It also adds and implements the logic for the load more button. 
Addresses #92
=> 92 create advanced user filtering

backend/dist/controllers/AuthController.js, backend/dist/controllers/ScheduleController.js, backend/dist/routes/scheduleRoute.js, backend/src/controllers/AuthController.ts, backend/src/controllers/ScheduleController.ts, backend/src/routes/scheduleRoute.ts, client/src/components/Login/LoginForm.tsx, client/src/components/Toggle.tsx, client/src/redux/slices/SchedulesSlice.ts
=> Refactored Backend + Client Sync (JWT)

client/src/components/Schedule/ScheduleBox.tsx, client/src/components/Schedule/TimeSlot.tsx, client/src/pages/Schedule.tsx
This PR adds the logic for rendering the time slots in the schedule. It adds the <hr /> tags and other styling to the schedule too. 
Addresses #99
=> 99 add time slot to schedule

client/src/components/Schedule/TimeSlot.tsx, client/src/pages/Schedule.tsx
=> loaded user schedule with RTK Query

backend/dist/server.js, backend/src/server.ts, client/src/App.tsx, client/src/components/Schedule/TimeSlotInput.tsx, client/src/pages/Schedule.tsx, client/src/redux/services/auth/authService.ts, client/src/redux/services/schedule/scheduleService.ts, client/src/redux/store.ts
=> 111 create timeslot rtk query

client/src/components/Account/Friends/FriendsTab.tsx, client/src/components/Account/Profile/ProfilePic.tsx, client/src/components/Auth/GoogleAuth.tsx, client/src/components/Login/LoginBox.tsx, client/src/components/Login/LoginForm.tsx, client/src/components/Logos/Edit.tsx, client/src/components/Logos/Github.tsx, client/src/components/Logos/Moon.tsx, client/src/components/Logos/Sun.tsx, client/src/components/Navbar.tsx, client/src/components/Schedule/ScheduleBox.tsx, client/src/components/Schedule/TimeSlot.tsx, client/src/components/Schedule/TimeSlotInput.tsx, client/src/components/Signup/SignUpForm.tsx, client/src/components/Utils/ColorsPalette.tsx, client/src/components/findUsers/UserContainer.tsx, client/src/pages/FindUser.tsx, client/src/pages/Login.tsx, client/src/pages/Schedule.tsx, client/src/redux/feats/auth/authActions.ts, client/src/redux/feats/auth/authSlice.ts, client/src/redux/feats/schedule/scheduleSlice.ts, client/src/redux/services/schedule/scheduleService.ts, client/src/types.ts
=> 113 typescript types file

client/src/components/Schedule/DaysChecked.tsx, client/src/components/Schedule/TimeSlot.tsx, client/src/components/Schedule/TimeSlotInput.tsx, client/src/pages/Schedule.tsx, client/src/redux/services/schedule/scheduleService.ts, client/src/types.ts
_**(PATCH isn't working only made UI for patch)**_
=> 115 delete timeslot rtk query

backend/dist/controllers/ScheduleController.js, backend/dist/routes/scheduleRoute.js, backend/src/controllers/ScheduleController.ts, backend/src/routes/scheduleRoute.ts, client/src/App.tsx, client/src/components/Schedule/ScheduleBox.tsx, client/src/components/Schedule/TimeSlot.tsx, client/src/components/Schedule/TimeSlotInput.tsx, client/src/components/findUsers/User.tsx, client/src/main.tsx, client/src/pages/CompareSchedule.tsx, client/src/pages/Schedule.tsx
Adding the compare schedules page which allows the user to see their schedule, the schedule of the user that they are comparing their schedule against and a view of the free time slots between the two users as well as how the two schedules of the users overlap with each other. It also adds logic to compare the schedules of two users and find the free times between the two. 
Addresses #76
=> 76 compare timeslots

client/src/components/Schedule/ScheduleBox.tsx, client/src/components/Schedule/TimeSlot.tsx, client/src/redux/feats/schedule/scheduleSlice.ts
- This PR fixes the issues that occurred when merging into the dev-branch in the previous PR.
=> Fix issues

client/src/components/Schedule/ScheduleBox.tsx, client/src/components/Schedule/TimeSlot.tsx, client/src/components/Schedule/TimeSlotInput.tsx, client/src/pages/Schedule.tsx, client/src/redux/services/schedule/scheduleService.ts, client/src/redux/store.ts
Adding cache invalidation to the scheduleService.ts file so that a refresh is not needed after performing a CRUD operation in the time slots.
=> Replace refresh

backend/dist/controllers/UserController.js, backend/dist/routes/userRoute.js, backend/src/controllers/UserController.ts, backend/src/routes/userRoute.ts, client/src/components/Account/Personal/PersonalTab.tsx, client/src/components/Account/Profile/ProfilePic.tsx, client/src/components/Account/Profile/ProfileTab.tsx, client/src/components/Schedule/TimeSlotInput.tsx, client/src/components/findUsers/UserContainer.tsx, client/src/redux/services/user/userService.ts, client/src/redux/store.ts
=> Crud users rtk

client/index.html, client/src/components/Navbar.tsx, client/src/pages/Homepage.tsx
This PR adds a favicon and title to the website.
=> 139 add favicon and change website title

README.md, client/src/components/Account/Personal/PersonalTab.tsx, client/src/pages/Login.tsx, client/src/types.ts
Fixed two PATCH updates on account settings
1. PATCH Gender
2. PATCH Date of Birth
=> 146 patch bugs on client

README.md, backend/dist/controllers/AuthController.js, backend/src/controllers/AuthController.ts, backend/src/models/userModel.ts, client/src/components/Navbar.tsx, client/src/components/Signup/SignUpForm.tsx, client/src/components/findUsers/User.tsx, client/src/components/findUsers/UserContainer.tsx, client/src/pages/CompareSchedule.tsx, client/src/redux/feats/auth/authActions.ts, client/src/redux/services/auth/authService.ts, client/src/redux/services/schedule/scheduleService.ts, client/src/redux/services/user/userService.ts, client/src/types.ts, client/src/utils/environment.ts
I'm trying to add a default profile picture for new users. However, when I make an new user object, the property photoURL is left null. Can you please check out the branch and debug it for me? I can't seem to get it working.
Files
Client -> `SignUpForm.tsx`
Backend -> `AuthController.ts`
Please either leave request changes with the potential solutions or commit to this branch. You can also see the changes on Netlify I believe below on the comment.
1. `git fetch origin`
2. `git checkout 142-add-default-profile-picture-on-new-accounts`
3. `git pull origin`
5. Debug!
=> 142 add default profile picture on new accounts

client/src/App.tsx, client/src/components/Login/LoginBox.tsx, client/src/components/Schedule/ScheduleBox.tsx, client/src/components/Schedule/TimeSlot.tsx, client/src/components/Schedule/TimeSlotInput.tsx, client/src/components/Signup/SignUpBox.tsx, client/src/components/Signup/SignUpForm.tsx, client/src/components/Toggle.tsx, client/src/pages/CompareSchedule.tsx, client/src/pages/LandingPage.tsx, client/src/pages/Login.tsx, client/src/pages/Schedule.tsx, client/src/pages/Signup.tsx
Responsive styles have been added to all the pages of the application so that it looks food on smaller screens. 
**Landing Page**
**My Schedule Page**
**Compare Schedule Page**
**Sign Up Page**
**Login Page**
=> 132 fix responsiveness of the schedule and landing pages

client/src/components/Account/Friends/FriendsTab.tsx, client/src/components/Account/Personal/PersonalTab.tsx, client/src/components/Account/Profile/ProfileTab.tsx, client/src/components/Login/LoginForm.tsx, client/src/components/Schedule/TimeSlot.tsx, client/src/components/Schedule/TimeSlotInput.tsx, client/src/pages/ForgotPassword.tsx
This issue fixes all hover buttons throughout the application
=> Fixed active hover buttons across app

client/src/components/Schedule/ClearScheduleButton.tsx
Fixed light mode unreadable text on clear schedule modal
=> 179 fix clear schedule modal in light mode

client/src/components/Toggle.tsx, client/src/enums.ts, client/src/pages/LandingPage.tsx, client/src/utils/functions.ts
This PR fixes the dark theme toggle functionality so that it persists across pages and refreshes. 
Important changes this PR makes:
- Uses LocalStorage to store the selected theme by the user. 
- Changes the state for dark mode in the `<Toggle />` component to be a `boolean` instead of a `string`. 
- Adds a enum and functions files to store enums and function utils that can be re-usable in different parts of the codebase.
Fixes #150 
https://github.com/KyoshiNoda/ScheduleFinder/assets/62437724/1e099952-0b50-415d-8f29-2cfb97a40429
The video has a watermark cause I had to compress it cause file was too big for GitHub.
=> 150 fix broken dark theme toggle

client/src/pages/CompareSchedule.tsx
=> fixed problem

backend/dist/controllers/ScheduleController.js, backend/src/controllers/ScheduleController.ts, client/src/components/Schedule/ClearScheduleButton.tsx, client/src/components/Schedule/ScheduleBox.tsx, client/src/components/Schedule/TimeSlot.tsx, client/src/components/Schedule/TimeSlotInput.tsx, client/src/utils/environment.ts
Added check for empty schedule check. If true, disable button
https://github.com/KyoshiNoda/ScheduleFinder/assets/62672803/c15a40ea-ddda-4c4c-b13b-e67495cb614a
I had to change the backend slightly so it renders a single schedule.
=> 182 empty schedule clear

backend/dist/controllers/ScheduleController.js, backend/dist/controllers/UserController.js, backend/src/controllers/ScheduleController.ts, backend/src/controllers/UserController.ts, client/src/components/Account/Personal/PersonalTab.tsx, client/src/components/Account/Profile/ProfileTab.tsx, client/src/components/Schedule/TimeSlotInput.tsx, client/src/pages/CompareSchedule.tsx
Fixed the response type from array with single items to just returning the single json entity. I also changed the UI portions that depended on the prior codebase `data[0]`
=> 198 fix return single element

backend/dist/controllers/UserController.js, backend/src/controllers/UserController.ts, client/src/components/Account/Profile/ProfileTab.tsx, client/src/components/Auth/ChangePassword.tsx, client/src/utils/environment.ts
Added Error Styles for `changePassword` on user settings.
=> 199 fix UI for change password

client/src/App.tsx, client/src/components/PageLayout.tsx, client/src/components/Toggle.tsx, client/src/pages/Account.tsx, client/src/pages/FindUser.tsx, client/src/pages/Notifications.tsx, client/src/pages/Schedule.tsx, client/src/utils/environment.ts
This PR moves the `<Toggle />` component to the `PageLayout` component so that it appears in every page without the need to manually include it. 
Fixes #189 
Also changed the import of the `<LandingPage />` component from Homepage to LandingPage in the `App` file.
=> 189 change location of the toggle component so that its not included in every file

client/src/components/Schedule/DayPicker.tsx, client/src/components/Schedule/TimeSlot.tsx, client/src/components/Schedule/TimeSlotInput.tsx, client/src/types.ts
- Refactored `TimeSlotInput.tsx` and `TimeSlot.tsx` by creating `DayPicker` component.  Prop drilling on both parent and child component.
- Reduced around **150** lines of code on both files.
#201
https://github.com/KyoshiNoda/ScheduleFinder/assets/62672803/a0cd8ec7-2735-4022-b6a8-efe6eb67cf5f
=> 201 refactor day picker from timeslots

client/src/components/Schedule/TimeSlotInput.tsx, client/src/enums.ts
This PR fixes the input validation for the time slot inputs. It adds the appropriate color to show when the input is not correct.
Fixes #193 
https://github.com/KyoshiNoda/ScheduleFinder/assets/62437724/de5648d0-d030-49d9-bf1b-bb9aaba792f3
=> 193 fix form input validation for the time slot input component

client/src/components/Schedule/ScheduleBox.tsx, client/src/pages/CompareSchedule.tsx, client/src/pages/Schedule.tsx, client/src/utils/environment.ts
- This PR fixes the compare schedule bug. The error was that the `data.timeSlots` was missing a final `s`.
- Refactored the `Schedule` and `ScheduleBox` components to fetch the data in the parent component and pass it as props. 
Fixes #208
=> 208 compare schedule page fix

client/src/components/Schedule/ScheduleBox.tsx, client/src/pages/Schedule.tsx
Reverted changes to fix auto-refresh for CRUD operations for time slots.
=> Fixed auto-refresh for time slot CRUD operations.

client/src/components/Schedule/TimeSlotInput.tsx
This PR fixes the input validation of the time slot input and makes the time range interval between
7:00 AM - 9:00 PM.
Addresses #216
=> 216 timeslot interval fix

client/src/components/Schedule/TimeSlotInput.tsx
PR to hopefully fix everything
=> Hopefully fix

backend/dist/controllers/UserController.js, backend/src/controllers/UserController.ts, client/src/components/Account/Personal/PersonalTab.tsx, client/src/components/Account/Profile/ProfilePic.tsx, client/src/components/Account/Profile/ProfileTab.tsx, client/src/redux/services/user/userService.ts, client/src/utils/environment.ts
Created UI for editing a profile picture. Users are now allowed to change their profile pictures. 
**_NOTE_**: I didn't implement remove profile picture because we are going to replace the whole UI for Settings for user profile page in issue #224 
https://github.com/KyoshiNoda/ScheduleFinder/assets/62672803/ba490bc3-80dd-4a57-9f69-89d6d6d52abb
=> 224 create UI for profile picture

client/src/components/Account/Personal/PersonalTab.tsx, client/src/components/Account/Profile/ProfilePic.tsx, client/src/components/Account/Profile/ProfileTab.tsx, client/src/components/Schedule/TimeSlotInput.tsx, client/src/redux/feats/auth/authActions.ts, client/src/redux/feats/auth/authSlice.ts, client/src/redux/services/user/userService.ts
Fixed NavBar redux problem. This issue now updates the store correctly and listens to the appropriate event handlers.
#236 
https://github.com/KyoshiNoda/ScheduleFinder/assets/62672803/be0e9dc6-e0d9-495b-b293-d8e446adbc87
-  [x] 🙋 no, because I need help
=> 236 fix navbar refresh

backend/dist/controllers/FriendController.js, backend/dist/routes/friendRequestRoute.js, backend/src/controllers/FriendController.ts, backend/src/routes/friendRequestRoute.ts, client/src/components/findUsers/User.tsx, client/src/redux/services/user/userService.ts, client/src/utils/environment.ts
This feature allows user to cancel a send friend request!
The following recording verifies the data is pushed out correctly.
#178 
https://github.com/KyoshiNoda/ScheduleFinder/assets/62672803/01050000-88ff-4483-bbc3-f90705f2b1c2
TESTED with demo account and user friend is `Kyoshi`
=> Cancel friend request

backend/dist/controllers/AuthController.js, backend/dist/controllers/FriendController.js, backend/src/controllers/AuthController.ts, backend/src/controllers/FriendController.ts, client/src/pages/ResetPassword.tsx, client/src/utils/environment.ts
- Added email notification for new friend requests
- Improved UI for forgotPassword email
#175 
https://github.com/KyoshiNoda/ScheduleFinder/assets/62672803/9b312316-aa87-4dc7-9177-f4c387d14aa5
https://github.com/KyoshiNoda/ScheduleFinder/assets/62672803/9a3f7e7c-3689-47b9-858a-c4aa32aa4415
- I added UI improvements along with this story for forgotPassword
=> Email friend request

client/src/App.tsx, client/src/components/Navbar.tsx, client/src/pages/Friends.tsx
This PR moves the friends list to its own separate page.
Fixes: #246 
<details>
<summary>Light Mode</summary>
src="https://github.com/KyoshiNoda/ScheduleFinder/assets/62437724/f8ef2435-0140-4205-b568-4567f89d599c">
</details>
<details>
<summary>Dark Mode</summary>
src="https://github.com/KyoshiNoda/ScheduleFinder/assets/62437724/978a3ee2-4724-416a-ac35-3c1be3b308a0">
</details>
=> 246 add a page dedicated to friends

client/src/components/Account/AccountBox.tsx, client/src/components/Account/Hobbies/HobbiesTab.tsx, client/src/components/Account/Tab.tsx, client/src/enums.ts, client/src/pages/Friends.tsx, client/src/redux/services/hobbies/hobbyService.ts
- Created UI for `Hobby` feature
- added RTK services for hobby endpoints
- added Enum type for Hobbies
- Toast component updated with Buttons
- **_NOTES_**: Dummy data still being used, button aren't functional. Strictly UI.
#240 
https://github.com/KyoshiNoda/ScheduleFinder/assets/62672803/ea046f58-8b66-4bb5-9617-96d42782eff0
=> Tag creation

client/src/pages/Friends.tsx, client/src/pages/UserPage.tsx
- Added UI/UX changes to the codebase on friends feature. 
- Better navigation for friends. (Added a button to link to friend's profile and another button for compare schedule with that given friend) This provides better user experience. 
- Improved mobile styles for friends profile, friends list, and added time for mobile view.
https://github.com/KyoshiNoda/ScheduleFinder/assets/62672803/df7e203e-1cd7-4d48-a5ac-a45e1259521f
Fixes #263
=> Friends fixes

client/src/utils/environment.ts
- Production hotfix for friends styling #262
=> Production HotFix 

client/src/components/Account/AccountBox.tsx, client/src/components/Login/LoginBox.tsx, client/src/components/Login/LoginForm.tsx, client/src/components/Navbar.tsx, client/src/components/PageLayout.tsx, client/src/components/Schedule/ScheduleBox.tsx, client/src/components/Schedule/TimeSlotInput.tsx, client/src/components/Signup/SignUpBox.tsx, client/src/components/Signup/SignUpForm.tsx, client/src/components/Toggle.tsx, client/src/components/UserPage/LoadingUserPage.tsx, client/src/components/UserPage/UserPageBox.tsx, client/src/enums.ts, client/src/pages/Account.tsx, client/src/pages/CompareSchedule.tsx, client/src/pages/FindUser.tsx, client/src/pages/ForgotPassword.tsx, client/src/pages/Friends.tsx, client/src/pages/LandingPage.tsx, client/src/pages/Login.tsx, client/src/pages/Notifications.tsx, client/src/pages/Schedule.tsx, client/src/pages/Signup.tsx, client/src/pages/UserPage.tsx, client/src/utils/functions.ts
- Revamped light mode 
-  Introduced **_System Preferences_**, Toggle now has three options
- Changed every light mode theme across the whole application.
Addresses #267 
https://github.com/KyoshiNoda/ScheduleFinder/assets/62672803/c69d715c-a000-414e-b9a5-69e5e6ee699f
=> Improved light mode

client/src/App.tsx, client/src/pages/AccountPage.tsx, client/src/pages/CompareSchedulePage.tsx, client/src/pages/FindUserPage.tsx, client/src/pages/ForgotPasswordPage.tsx, client/src/pages/FriendsListPage.tsx, client/src/pages/LoginPage.tsx, client/src/pages/NotificationsListPage.tsx, client/src/pages/ResetPasswordPage.tsx, client/src/pages/SchedulePage.tsx, client/src/pages/SignupPage.tsx, client/src/pages/UserProfilePage.tsx
- Added Page suffix to each parent page.
#290
=> Page suffix

client/src/components/Account/Hobbies/HobbiesTab.tsx, client/src/components/Account/Profile/ProfileTab.tsx, client/src/components/Modals/ChangePasswordModal.tsx, client/src/components/Modals/ClearScheduleModal.tsx, client/src/components/Modals/EditTimeSlotModal.tsx, client/src/components/Modals/ExisitingTImeSlotModal.tsx, client/src/components/Modals/FriendRemovalModal.tsx, client/src/components/Modals/HobbiesRemovalModal.tsx, client/src/components/Navbar.tsx, client/src/components/Schedule/ClearScheduleButton.tsx, client/src/components/Schedule/ScheduleBox.tsx, client/src/components/Schedule/TimeSlot.tsx, client/src/components/Schedule/TimeSlotInput.tsx, client/src/components/Toggle.tsx, client/src/pages/Friends.tsx, client/src/types.ts, client/src/utils/functions.ts
- This pull request handles refactoring of modals
- Created a folder called Modals and made each Modal with the logic attached to its own component
- Added escape accessibility on modal exits.
- On modal open, and escape key pressed the modal will exist. 
- We can change this for modal that should not be escaped by removing 
`useEscapeKey(() => setOpenModal(false));` on a given `Modal` component
- `Toggle` component dark mode dropdown fix.
- #278 
- #276   
- #288 
- Can't really show me clicking escape. But on escape it does exit the modal with clicking on it
https://github.com/KyoshiNoda/ScheduleFinder/assets/62672803/63f28c88-0191-4ff3-9b29-baa91d0962eb
=> Modal accessibility

client/src/pages/FriendsListPage.tsx, client/src/pages/NotificationsListPage.tsx
- Small pull request to add scrollable lists for friend requests, and friends list. Used for large amount of data bigger than the screen itself.
- [] 🍕 Feature
#277 
https://github.com/KyoshiNoda/ScheduleFinder/assets/62672803/0f7363aa-b7bc-4296-b16a-ee09e3af2f6c
=> Scrollable list

backend/dist/controllers/AuthController.js, backend/dist/routes/authRoute.js, backend/src/controllers/AuthController.ts, backend/src/routes/authRoute.ts, client/package-lock.json, client/package.json, client/src/components/PageLayout.tsx, client/src/pages/UnauthorizedPage.tsx, client/src/redux/feats/auth/authSlice.ts, client/src/utils/environment.ts
- Added JWT expirations
- Added 401 Unauthorized Page UI 
- Supports 1 Day currently expiration.
#269 
https://github.com/KyoshiNoda/ScheduleFinder/assets/62672803/faa06ade-c42d-4960-aa99-58ca371cb394
=> Jwt expire

client/package-lock.json, client/package.json, client/src/components/Calendar/CalendarViewParent.tsx, client/src/components/Calendar/Views/MonthlyView.tsx, client/src/pages/SchedulePage.tsx, client/src/utils/scheduleUtils.ts
- Added monthly view for the new schedule app.
#286
=> Monthly view

client/package-lock.json, client/package.json, client/src/components/Account/AccountBox.test.tsx, client/vitest.config.ts
- Setup FRONTEND unit testing. I decided to go with [Vitest](https://vitest.dev/) because our project is configured with vite so it would make the most "sense" however, we can look into other ones. But from what it seems it works well with **Jest** and **Testing Library**. 
- This pull request, contains one unit test for `AccountBox`. I will open up more stories to continue testing.
- To start up unit testing, run the following commands on the **CLIENT** directory . I believe it will run through all existing tests
- `npm run test` this will just have a terminal view of your passing/failing tests
- `npm run test:ui` this will open a server on your broswer where you can see a better view of the passing/failing tests with things such as debugger (See DOM elements and visual graph)
- …
=> 300-Setup-unit-test
